"""
report.py — PDF report download endpoint for the RiskLens API.

Accepts a ``ReportRequest`` payload (patient details, prediction results,
SHAP data) and returns a downloadable clinical PDF generated by
``pdf_generator.generate_report``.
"""

from __future__ import annotations

import logging
from typing import Any

from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
import io

from api.pdf_generator import generate_report

logger = logging.getLogger("risklens.report")

router = APIRouter(prefix="/api", tags=["report"])


# ---------------------------------------------------------------------------
# Request models
# ---------------------------------------------------------------------------
class DriverInfo(BaseModel):
    """A single risk-driver entry (matches ``DriverDetail`` from predict.py)."""
    feature: str
    featureLabel: str = ""
    value: float = 0.0
    shapValue: float = 0.0
    direction: str = "risk"


class ReportRequest(BaseModel):
    """Everything needed to generate the PDF report.

    The front-end collects this from the prediction response plus patient
    form fields and posts it to ``/api/report/pdf``.
    """
    patientName: str = Field(..., min_length=1, max_length=200, description="Patient full name")
    patientEmail: str = Field("", description="Patient email (optional)")
    riskScore: int = Field(..., ge=0, le=100, description="Risk score 0-100")
    riskLevel: str = Field(..., description="Low / Moderate / High")
    clinicalAction: str = Field("", description="Clinical recommendation text")
    inputs: dict[str, Any] = Field(default_factory=dict, description="Original 21 BRFSS input values")
    shapValues: dict[str, float] = Field(default_factory=dict, description="All SHAP values")
    topDrivers: list[DriverInfo] = Field(default_factory=list, description="Top risk-increasing drivers")
    protectiveFactors: list[DriverInfo] = Field(default_factory=list, description="Top protective factors")


# ---------------------------------------------------------------------------
# Endpoint
# ---------------------------------------------------------------------------
@router.post("/report/pdf")
async def download_pdf_report(request: ReportRequest):
    """Generate and return a downloadable PDF report.

    Returns:
        StreamingResponse with ``application/pdf`` content type and a
        ``Content-Disposition`` header for browser download.
    """
    try:
        logger.info(
            "Generating PDF report for patient=%s risk=%d/%s",
            request.patientName,
            request.riskScore,
            request.riskLevel,
        )

        # Convert Pydantic models to plain dicts for the PDF generator
        top_drivers_dicts = [d.model_dump() for d in request.topDrivers]
        protective_dicts = [d.model_dump() for d in request.protectiveFactors]

        pdf_bytes = generate_report(
            patient_name=request.patientName,
            patient_email=request.patientEmail,
            risk_score=request.riskScore,
            risk_level=request.riskLevel,
            clinical_action=request.clinicalAction,
            inputs_dict=request.inputs,
            shap_values_dict=request.shapValues,
            top_drivers=top_drivers_dicts,
            protective_factors=protective_dicts,
        )

        logger.info("PDF generated successfully (%d bytes)", len(pdf_bytes))

        # Sanitise filename
        safe_name = "".join(
            c if c.isalnum() or c in (" ", "-", "_") else "_"
            for c in request.patientName
        ).strip()
        filename = "risklensreport.pdf"

        return StreamingResponse(
            io.BytesIO(pdf_bytes),
            media_type="application/pdf",
            headers={
                "Content-Disposition": f'attachment; filename="risklensreport.pdf"',
                "Content-Length": str(len(pdf_bytes)),
            },
        )

    except Exception as exc:
        logger.exception("Failed to generate PDF report")
        raise HTTPException(
            status_code=500,
            detail=f"Failed to generate PDF report: {str(exc)}",
        ) from exc
